### ISSUE TITLE
Build failed with docker-compose error

### ISSUE THREAD

**Issue by jordanschalm** [ubclaunchpad/inertia#181]
`inertia <remote> up` fails with error:
```
<The Compose file './docker-compose.yml' is invalid because:
Dservices.base.ports contains an invalid type, it should be an array
[ERROR 500] Build exited with non-zero status: 1
```

This same docker-compose file works fine with `docker-compose` version 1.21.0 locally.

I've tried with two different docker-compose file layouts:
1.
```
version: '3'

services:
  base:
    image: jordanschalm/base
    ports: ["80:80", "443:443", "9001:9001"]
```

2.
```
version: '3'

services:
  base:
    image: jordanschalm/base
    ports:
      - "80:80"
      - "443:443"
      - "9001:9001"
```
